// Comuni italiani - lista per autocomplete del campo città in registrazione.
// Include tutti i capoluoghi di provincia + i comuni più popolati (>10k abitanti).
// Per la lista ISTAT completa (~7.900 comuni) integrare in futuro un fetch al dataset ufficiale.

const COMUNI_ITALIANI = [
  'Abano Terme','Abbiategrasso','Acerra','Aci Castello','Aci Catena','Acireale','Acqui Terme','Adrano','Afragola',
  'Agrigento','Agropoli','Alba','Albano Laziale','Albenga','Alcamo','Alessandria','Alghero','Alpignano','Altamura',
  'Altavilla Vicentina','Amalfi','Amelia','Anagni','Ancona','Andria','Anzio','Aosta','Aprilia','Aquila','Arese',
  'Arezzo','Argenta','Ariano Irpino','Ariccia','Arona','Arzano','Ascoli Piceno','Asola','Assemini','Assisi','Asti',
  'Augusta','Aversa','Avezzano','Avellino','Avigliana','Bacoli','Bagheria','Bagnacavallo','Bagno a Ripoli','Bari',
  'Barletta','Barcellona Pozzo di Gotto','Bassano del Grappa','Battipaglia','Belluno','Benevento','Bergamo','Bibbiena',
  'Biella','Bisceglie','Bitonto','Bitritto','Bivona','Bologna','Bolzano','Bordighera','Borgaro Torinese','Borgomanero',
  'Borgonovo Val Tidone','Boscoreale','Boscotrecase','Botticino','Bra','Brescia','Brindisi','Bronte','Bussolengo',
  'Busto Arsizio','Cagliari','Calcinato','Caltagirone','Caltanissetta','Camaiore','Campi Bisenzio','Campobasso',
  'Campodarsego','Campofelice di Roccella','Cannara','Canosa di Puglia','Cantù','Capannori','Capoterra','Capua',
  'Carini','Carmagnola','Carpi','Carrara','Casalecchio di Reno','Casalgrande','Casalmaggiore','Casalnuovo di Napoli',
  'Casalpusterlengo','Casarano','Caserta','Casoria','Cassano Magnago','Cassano allo Ionio','Cassino','Castel San Giorgio',
  'Castel Volturno','Castelfidardo','Castelfranco Emilia','Castelfranco Veneto','Castellammare di Stabia','Castellamonte',
  'Castellanza','Castelvetrano','Castiglione delle Stiviere','Castrovillari','Catania','Catanzaro','Cattolica','Cava de Tirreni',
  'Cecina','Cefalù','Celano','Cerea','Cerignola','Cernusco sul Naviglio','Cerveteri','Cesano Boscone','Cesano Maderno',
  'Cesena','Cesenatico','Chiavari','Chieri','Chieti','Chioggia','Chivasso','Cinisello Balsamo','Cisterna di Latina',
  'Città di Castello','Cittadella','Civita Castellana','Civitanova Marche','Civitavecchia','Cles','Cocquio-Trevisago',
  'Cogoleto','Collegno','Colleferro','Collegnò','Comacchio','Como','Conegliano','Conversano','Copparo','Corato',
  'Cordenons','Corigliano-Rossano','Cormano','Cornaredo','Corropoli','Corsico','Cortina d\'Ampezzo','Cosenza','Cremona',
  'Crotone','Cuneo','Curtatone','Cusano Milanino','Dalmine','Desenzano del Garda','Desio','Domodossola','Empoli',
  'Enna','Ercolano','Erice','Eboli','Faenza','Falconara Marittima','Fano','Fasano','Favara','Fermo','Ferrara',
  'Fidenza','Fiesole','Figline e Incisa Valdarno','Finale Emilia','Finale Ligure','Fiorano Modenese','Firenze','Fiumicino',
  'Foggia','Foiano della Chiana','Foligno','Follonica','Fondi','Fonte Nuova','Formia','Forlì','Formigine','Francavilla al Mare',
  'Francavilla Fontana','Frascati','Frosinone','Gaeta','Galatina','Galliate','Gallarate','Gallipoli','Garbagnate Milanese',
  'Gela','Gemona del Friuli','Genova','Genzano di Roma','Ghedi','Giarre','Ginosa','Gioia del Colle','Gioia Tauro','Giugliano in Campania',
  'Giulianova','Gorizia','Gravina di Catania','Gravina in Puglia','Grosseto','Grottaferrata','Grottaglie','Grugliasco','Gualdo Tadino',
  'Guastalla','Guidonia Montecelio','Iglesias','Imola','Imperia','Inzago','Iseo','Isernia','Ispra','Ivrea','Jesi',
  'La Spezia','Ladispoli','L\'Aquila','Lainate','Lamezia Terme','Lampedusa e Linosa','Lanciano','Larino','Lastra a Signa',
  'Latina','Latisana','Lecce','Lecco','Legnago','Legnano','Lentini','Licata','Lignano Sabbiadoro','Limbiate','Lissone',
  'Livorno','Locri','Lodi','Lonate Pozzolo','Loreto','Loreto Aprutino','Lucca','Lugo','Macerata','Magenta','Maglie','Malnate',
  'Manfredonia','Manduria','Mantova','Manzano','Marano di Napoli','Marcianise','Mariano Comense','Marigliano','Marino',
  'Marsala','Martina Franca','Martinsicuro','Massa','Massafra','Massa Lombarda','Matera','Mazara del Vallo','Mazzo di Valtellina',
  'Mediglia','Melegnano','Melfi','Melilli','Mentana','Merano','Mercato San Severino','Mesagne','Messina','Mestre','Mezzocorona',
  'Milano','Milazzo','Mira','Mirandola','Misilmeri','Misterbianco','Modena','Modica','Modugno','Mogliano Veneto','Molfetta',
  'Moncalieri','Mondovì','Mondragone','Monfalcone','Monopoli','Monreale','Monselice','Montale','Montebelluna','Montecatini Terme',
  'Montechiarugolo','Monte di Procida','Monte Sant\'Angelo','Monteforte Irpino','Montegrotto Terme','Monteprandone','Monterotondo',
  'Montesilvano','Montichiari','Montorio al Vomano','Monza','Mortara','Motta di Livenza','Mottola','Mugnano di Napoli','Muggiò',
  'Naro','Nettuno','Niscemi','Nocera Inferiore','Nocera Umbra','Noci','Noicattaro','Nola','Novara','Novate Milanese','Novi Ligure',
  'Numana','Nuoro','Olbia','Oleggio','Oliveri','Opera','Orbetello','Orgosolo','Oristano','Orvieto','Orzinuovi','Osimo','Ostia',
  'Ostuni','Pachino','Padova','Paderno Dugnano','Padula','Pagani','Palagiano','Palazzolo sull\'Oglio','Palermo','Palestrina',
  'Palmi','Palo del Colle','Palombara Sabina','Parabiago','Parma','Partinico','Paternò','Pavia','Pavullo nel Frignano','Pellezzano',
  'Penne','Perugia','Pesaro','Pescara','Peschiera Borromeo','Peschiera del Garda','Pessano con Bornago','Petilia Policastro',
  'Piacenza','Piedimonte Matese','Pietrasanta','Pieve di Soligo','Pieve Emanuele','Pinerolo','Pioltello','Piombino',
  'Pioltello','Pisa','Pistoia','Poggibonsi','Poggiomarino','Pomezia','Pompei','Pomigliano d\'Arco','Pontassieve','Ponte San Pietro',
  'Pontecagnano Faiano','Pordenone','Porto Sant\'Elpidio','Porto Torres','Portici','Portogruaro','Portoferraio','Potenza','Pozzallo',
  'Pozzuoli','Prato','Quartu Sant\'Elena','Quarto','Quartucciu','Quistello','Racconigi','Ragusa','Randazzo','Rapallo','Ravanusa',
  'Ravenna','Recanati','Reggio Calabria','Reggio Emilia','Rende','Resana','Rezzato','Rho','Riccione','Rieti','Rimini','Riposto',
  'Riva del Garda','Rivalta di Torino','Rivoli','Roma','Romano di Lombardia','Roncade','Roseto degli Abruzzi','Rosignano Marittimo',
  'Rosolini','Rovato','Rovereto','Rovigo','Rozzano','Rubiera','Saint-Vincent','Salerno','Salò','Saluzzo','San Benedetto del Tronto',
  'San Bonifacio','San Cataldo','San Cesareo','San Donà di Piave','San Donato Milanese','San Felice Circeo','San Felice sul Panaro',
  'San Ferdinando di Puglia','San Gennaro Vesuviano','San Giorgio a Cremano','San Giorgio Ionico','San Giovanni in Persiceto',
  'San Giovanni Lupatoto','San Giovanni Rotondo','San Giovanni Valdarno','San Giovanni la Punta','San Giuliano Milanese',
  'San Giuliano Terme','San Giuseppe Jato','San Giuseppe Vesuviano','San Lazzaro di Savena','San Marcellino','San Marco in Lamis',
  'San Martino Buon Albergo','San Mauro Torinese','San Miniato','San Nicola la Strada','San Pietro Vernotico','San Salvo',
  'San Sebastiano al Vesuvio','San Severo','San Vincenzo','San Vito al Tagliamento','San Vito dei Normanni','Sannicola','Sansepolcro',
  'Santa Croce sull\'Arno','Santa Maria Capua Vetere','Santa Maria a Vico','Santa Marinella','Santa Teresa Gallura','Santarcangelo di Romagna',
  'Sant\'Agata di Militello','Sant\'Anastasia','Sant\'Antimo','Sant\'Antioco','Sant\'Arpino','Sant\'Egidio alla Vibrata','Sant\'Elpidio a Mare',
  'Saronno','Sarzana','Sassari','Sassuolo','Savigliano','Savona','Scafati','Scandiano','Scandicci','Sciacca','Scordia','Segrate',
  'Selargius','Senago','Senigallia','Seregno','Seriate','Sesto Calende','Sesto Fiorentino','Sesto San Giovanni','Sestri Levante',
  'Sestu','Settimo Milanese','Settimo Torinese','Seveso','Sezze','Siena','Silvi','Sinnai','Siracusa','Siniscola','Solaro','Solofra',
  'Somma Vesuviana','Somma Lombardo','Sondrio','Soncino','Sora','Soresina','Soverato','Spinea','Spoleto','Squinzano','Sulmona',
  'Surbo','Susa','Taormina','Taranto','Tarcento','Taurianova','Teano','Telese Terme','Teramo','Terlizzi','Termini Imerese','Termoli',
  'Terni','Terracina','Tezze sul Brenta','Thiene','Tivoli','Todi','Tolentino','Torino','Torrazza Coste','Torre Annunziata','Torre del Greco',
  'Torre Santa Susanna','Torremaggiore','Torrita di Siena','Tortolì','Tortona','Trani','Trapani','Trecate','Trecastagni','Trento','Trentola Ducenta',
  'Trevi','Treviglio','Treviso','Trezzo sull\'Adda','Trieste','Trinitapoli','Triggiano','Tropea','Udine','Ugento','Urbania','Urbino','Vado Ligure',
  'Vairano Patenora','Valdagno','Valenza','Valmadrera','Valmontone','Varese','Vasto','Velletri','Venezia','Venafro','Venaria Reale',
  'Ventimiglia','Vercelli','Verona','Veroli','Vetralla','Viareggio','Vibo Valentia','Vicenza','Vico Equense','Vigevano','Vignola',
  'Villa San Giovanni','Villaricca','Villasanta','Villasor','Vimercate','Vimodrone','Vinci','Vincenza','Viterbo','Vittoria','Vittorio Veneto',
  'Voghera','Volla','Volpiano','Volterra',
].sort((a, b) => a.localeCompare(b, 'it'))

export default COMUNI_ITALIANI
